## -*- python -*-

import sys
import os.path
import os
import pproc as subprocess


def build(bld):
    gen = bld.create_obj('command-output')
    gen.command = 'test-generation.py'
    gen.stdout = 'test.cc'
    gen.stdin = 'test-generation.py'
    top_srcdir = bld.m_srcnode.abspath()
    gen.argv = [top_srcdir]
    gen.priority = 5
    
    obj = bld.create_obj('cpp', 'objects', 'pyext')
    obj.source = 'test.cc'
    obj.env.append_value('CXXFLAGS', ['-Wall', '-Werror', '-Wno-unused'])

    cwd = os.getcwd()
    env = dict(os.environ)
    env['PYTHONPATH'] = top_srcdir
    os.chdir(top_srcdir)
    try:
        if subprocess.Popen(['python', 'tests/test.py'], env=env).wait():
            raise SystemExit(1)
    finally:
        os.chdir(cwd)

