## -*- python -*-
import Action
import Object
import Params
import Task


def build(bld):
    bindgen = bld.create_obj('command-output')
    bindgen.stdout = 'foomodule.cc'
    bindgen.stdin = 'foomodulegen.py'
    bindgen.command = 'foomodulegen.py'
    bindgen.prio = 3 # must run after the 'py' objects in ../pybindgen

    obj = bld.create_obj('cpp', 'shlib', 'pyext')
    obj.source = [
        'foo.cc',
        'foomodule.cc'
        ]
    obj.target = 'foo'

    ## Workaround a WAF bug (http://code.google.com/p/waf/issues/detail?id=37)
    obj.env.append_value("CPPPATH", bld.m_curdirnode.srcpath(obj.env))

