## -*- python -*-

def build(bld):

    gen = bld.new_task_gen(
        features='command',
        source='modulegen.py',
        target='hmodule.cc',
        command='${PYTHON} ${SRC[0]} > ${TGT[0]}')

    if bld.env['CXX']:
        obj = bld.new_task_gen('cxx', 'shlib', 'pyext')
        obj.source = [
            'h.cc',
            'hmodule.cc'
            ]
        obj.target = 'h'
        obj.install_path = None # do not install
        obj.includes = '.'

