## -*- python -*-

def build(bld):
    
    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('.')
    obj.source.append('version.py')
    obj.install_path = '${PYTHONDIR}/pybindgen'
    obj.prio = 50

    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('typehandlers')
    obj.install_path = '${PYTHONDIR}/pybindgen/typehandlers'
    obj.prio = 50

    obj = bld.new_task_gen('py')
    obj.find_sources_in_dirs('typehandlers/ctypeparser')
    obj.install_path = '${PYTHONDIR}/pybindgen/typehandlers/ctypeparser'
    obj.prio = 50
