## -*- python -*-

def build(bld):
    
    obj = bld.create_obj('py')
    obj.find_sources_in_dirs('.')
    # commented, triggers a WAF bug (Issue #40)
    #obj.source.append('version.py')
    obj.inst_dir = 'pybindgen'

    obj = bld.create_obj('py')
    obj.find_sources_in_dirs('typehandlers')
    obj.inst_dir = 'pybindgen/typehandlers'

